USE acme_space;

INSERT INTO acme_basic_geom (geom_cd, geom_name, geom_num, create_time, create_user) VALUES ('N40','N40',0.04, '2014-09-20 22:00:01', 'CHLEEZO');
INSERT INTO acme_basic_geom (geom_cd, geom_name, geom_num, create_time, create_user) VALUES ('N32','N32',0.032, '2014-09-20 22:00:01', 'CHLEEZO');
INSERT INTO acme_basic_geom (geom_cd, geom_name, geom_num, create_time, create_user) VALUES ('N28','N28',0.028, '2014-09-20 22:00:01', 'CHLEEZO');